#ifndef OS_MEMORY_CALL_CODE
#define OS_MEMORY_CALL_CODE

#define CONTROL_UNOPENED_FILE_MEMORY_CALL_FROM_ROOT	0
#define CONTROL_UNOPENED_FILE_MEMORY_CALL		1
#define CONTROL_OPENED_FILE_MEMORY_CALL			2
#define OPEN_FILE_WINDOW_MEMORY_CALL			3
#define CLOSE_FILE_WINDOW_MEMORY_CALL			4
#define SETUP_MAP_MEMORY_CALL				5
#define FLUSH_PROCESS_MEMORY_CALL			6
#define FLUSH_FILE_WINDOW_MEMORY_CALL			7
#define QUERY_PROCESS_MEMORY_CALL			8
#define SET_PROCESS_MEMORY_CALL				9
#define QUERY_FILE_WINDOW_MEMORY_CALL			10
#define SET_FILE_WINDOW_MEMORY_CALL			11
#define WAKEUP_FILE_WINDOW_MEMORY_CALL			12
#define WAKEUP_MEMORY_DOMAIN_MEMORY_CALL		13
#define INIT_MEMORY_BODY				14
#define LINK_MEMORY_BODY				15

#endif
