#ifndef OS_KERNEL_CONST
#define OS_KERNEL_CONST

#define TRUE	(2<3)
#define FALSE	(3<2)

#define OS_CPU_NUMBER			7
#define OS_CPU_SET_NUMBER		3
#define OS_DOMAIN_NUMBER 		4
#define OS_THREAD_NUMBER		23

#define OS_RETURN_STACK_NUMBER		(OS_THREAD_NUMBER*60)
#define OS_SEMAPHORE_NUMBER		\
	(OS_THREAD_NUMBER+OS_DOMAIN_NUMBER+2*OS_RETURN_STACK_NUMBER)
#define OS_USER_FILE_NUMBER		6

#endif
