#ifndef OS_ROUTINE_CODE
#define OS_ROUTINE_CODE

#define IS_SYSTEM_CALL						0
#define IS_NO_LOCK_KERNEL_DROP					1
#define IS_NO_LOCK_KERNEL_CONTINUE_WAIT				2
#define IS_NO_LOCK_KERNEL_AS_SYSTEM_CALL_ONCE			3
#define IS_NO_LOCK_KERNEL_AS_SYSTEM_CALL_FOREVER		4

#endif
