#ifndef OS_SERVER_TYPE_DEFINATION
#define OS_SERVER_TYPE_DEFINATION

#define CHECK_POINT_REQUEST		0
#define FILE_OPERATION_REQUEST		1
#define SIGNAL_PROCESS_REQUEST		2
#define PROCESS_TIME_OUT_REQUEST	3
#define SHUTDOWN_REQUEST		4

#endif 
