#ifndef OS_SYSTEM_CALL_CODE
#define OS_SYSTEM_CALL_CODE

#define THREAD_CALL_SYSTEM_CALL			0
#define THREAD_JUMP_SYSTEM_CALL			1
#define WITH_BLOCK_THREAD_CALL_SYSTEM_CALL	2
#define THREAD_RETURN_SYSTEM_CALL		3
#define SEMAPHORE_INFORMATION_SYSTEM_CALL	4
#define SEMAPHORE_OPERATION_SYSTEM_CALL		5
#define SEMAPHORE_TIME_SYSTEM_CALL		6
#define CREATE_THREAD_SYSTEM_CALL		7
#define CREATE_REQUEST_THREAD_SYSTEM_CALL	8
#define CPU_SET_SYSTEM_CALL			9
#define SEND_SIGNAL_SYSTEM_CALL			10
#define RESOURCE_ALLOCATION_SYSTEM_CALL		11
#define RESOURCE_QUERY_SYSTEM_CALL		12
#define SEMAPHORE_ALLOCATION_SYSTEM_CALL	13
#define SEMAPHORE_RELEASE_SYSTEM_CALL		14
#define THREAD_SET_SYSTEM_CALL			15
#define THREAD_QUERY_SYSTEM_CALL		16
#define SYSTEM_FILE_SYSTEM_CALL			17
#define THREAD_FILE_SYSTEM_CALL			18
#define SHUTDOWN_SYSTEM_CALL			19

#endif 
